/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javagui2;

import javax.swing.JOptionPane;

/**
 *
 * @author ajid
 */
public class latihan_Implementasi_Scroolpane_scrollbar extends javax.swing.JFrame {

    /**
     * Creates new form latihan_Implementasi_Scroolpane_scrollbar
     */
    public latihan_Implementasi_Scroolpane_scrollbar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        popUpmenuAbout = new javax.swing.JMenuItem();
        popUpmenuExit = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        textInputNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pilihanPembayaran = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listBarang = new javax.swing.JList<>();
        labelNamapembeli = new javax.swing.JLabel();
        labelnamapembeli = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelMetodePembayaran = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textareaBarangPilihan = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuAbout = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();

        popUpmenuAbout.setText("About Aplikasi");
        popUpmenuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popUpmenuAboutActionPerformed(evt);
            }
        });
        popupMenu.add(popUpmenuAbout);

        popUpmenuExit.setText("Exit");
        popUpmenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popUpmenuExitActionPerformed(evt);
            }
        });
        popupMenu.add(popUpmenuExit);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        jLabel1.setText("Input Nama");

        textInputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textInputNamaActionPerformed(evt);
            }
        });

        jLabel2.setText("METODE");

        jLabel3.setText("PEMBAYARAN");

        pilihanPembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Via Indomaret", "Via alfamart", "Via Aplikasi Ovo", "Via Doku", "Transfer Bank BCA", "Transfer Bank BRI", "Transfer Bank MANDIRI", "Transfer Bank BNI", "Transfer Bank PERMATA", " " }));
        pilihanPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanPembayaranActionPerformed(evt);
            }
        });

        jLabel4.setText("Barang yang dibeli");

        listBarang.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Smarphone", "Laptop", "Baju", "Sepatu", "Celana", "Sepeda", "Motor", "Mobil", "Rumah", "Apartemen", "Ruko", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listBarang.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listBarangValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listBarang);

        labelNamapembeli.setText("Nama Pembeli           :");

        labelnamapembeli.setForeground(new java.awt.Color(51, 51, 255));
        labelnamapembeli.setText("tekan enter pada input nama");

        jLabel7.setText("Metode pembayaran:");

        labelMetodePembayaran.setForeground(new java.awt.Color(0, 153, 102));
        labelMetodePembayaran.setText("pilih metode pembayaran");

        jLabel9.setText("Barang Yang dibeli    ");

        textareaBarangPilihan.setColumns(20);
        textareaBarangPilihan.setRows(5);
        jScrollPane2.setViewportView(textareaBarangPilihan);

        jMenu1.setText("Main Menu");

        menuAbout.setText("About Aplikasi");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        jMenu1.add(menuAbout);

        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pilihanPembayaran, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(40, 40, 40)
                            .addComponent(textInputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNamapembeli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelnamapembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelMetodePembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textInputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pilihanPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNamapembeli)
                            .addComponent(labelnamapembeli))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(labelMetodePembayaran)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(null,"APLIKASI YANG MENGIMPLEMENTASIKAN SCROLLPANE \n DAN SCROLL BAR");
    }//GEN-LAST:event_menuAboutActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_menuExitActionPerformed

    private void textInputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textInputNamaActionPerformed
        // TODO add your handling code here:
        
        String nama;
        nama= textInputNama.getText();
        
        labelnamapembeli.setText(nama);
    }//GEN-LAST:event_textInputNamaActionPerformed

    private void pilihanPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanPembayaranActionPerformed
        // TODO add your handling code here:
        
        labelMetodePembayaran.setText((String) pilihanPembayaran.getSelectedItem());
    }//GEN-LAST:event_pilihanPembayaranActionPerformed

    private void listBarangValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listBarangValueChanged
        // TODO add your handling code here:
        
        Object[] itemDipilih=listBarang.getSelectedValues();
        
        if(itemDipilih == null || itemDipilih.length == 0){
            textareaBarangPilihan.setText(null);
        }else{
            
            StringBuilder barang=new StringBuilder();
            for(Object item : itemDipilih){
                
                StringBuilder append=barang.append(item.toString()).append("\n");
            }
            
            String text;
            text= "BARANG YANG ANDA PILIH\n\n";
            text += barang.toString();
            textareaBarangPilihan.setText(text);
        }
    }//GEN-LAST:event_listBarangValueChanged

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        
        if(evt.isPopupTrigger()){
            
            popupMenu.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_formMouseReleased

    private void popUpmenuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popUpmenuAboutActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(null,"APLIKASI YANG MENGIMPLEMENTASIKAN SCROLLPANE \n DAN SCROLL BAR");
    }//GEN-LAST:event_popUpmenuAboutActionPerformed

    private void popUpmenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popUpmenuExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_popUpmenuExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latihan_Implementasi_Scroolpane_scrollbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latihan_Implementasi_Scroolpane_scrollbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latihan_Implementasi_Scroolpane_scrollbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihan_Implementasi_Scroolpane_scrollbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new latihan_Implementasi_Scroolpane_scrollbar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelMetodePembayaran;
    private javax.swing.JLabel labelNamapembeli;
    private javax.swing.JLabel labelnamapembeli;
    private javax.swing.JList<String> listBarang;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JComboBox<String> pilihanPembayaran;
    private javax.swing.JMenuItem popUpmenuAbout;
    private javax.swing.JMenuItem popUpmenuExit;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JTextField textInputNama;
    private javax.swing.JTextArea textareaBarangPilihan;
    // End of variables declaration//GEN-END:variables
}
